services:
  # Backend service
  - type: web
    name: 2-squares-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
    
  # Frontend service  
  - type: web
    name: 2-squares-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    envVars:
      - key: BACKEND_HOST
        value: https://2-squares-backend.onrender.com